---
- name: ensure user account exists
  user:
    name: "{{ user_name }}"
- name: ensure source directory exists
  file:
    path: "{{ source_directory }}"
    owner: "{{ user_name }}"
    state: directory
- name: ensure Ghost is installed in source directory
  command: /bin/sh -lc "ghost install local"
  become: yes
  become_method: su
  become_user: "{{ user_name }}"
  args:
    chdir: "{{ source_directory }}"
    creates: "{{ source_directory }}/content"
- name: check if Ghost is running
  uri:
    url: "{{ ghost_address }}"
  register: ghost_running
  ignore_errors: yes
- name: stop Ghost before backup
  command: /bin/sh -lc "ghost stop"
  when: "ghost_running.status != -1"
  become: yes
  become_method: su
  become_user: "{{ user_name }}"
  args:
    chdir: "{{ source_directory }}"
- name: create archive
  archive:
    path: "{{ source_directory }}"
    dest: "{{ destination_file }}"
- name: restart Ghost after backup
  command: /bin/sh -lc "ghost start"
  when: restart_after_backup and ghost_running.status != -1
  become: yes
  become_method: su
  become_user: "{{ user_name }}"
  args:
    chdir: "{{ source_directory }}"
